import {
  Calculator,
  Code2,
  Type,
  Clock,
  HeartPulse,
  Percent,
  Fingerprint,
  Binary,
  Hash,
  LetterText,
  CaseSensitive,
  HelpCircle,
  Calendar,
  Ruler,
  Lock,
  Monitor,
  Layers,
  Palette,
  Search,
  FileText,
  ListTodo,
  Sparkles,
  Puzzle,
} from "lucide-react";
import type { ComponentType } from "react";

export const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  calculator: Calculator,
  code: Code2,
  type: Type,
  clock: Clock,
  "heart-pulse": HeartPulse,
  percent: Percent,
  fingerprint: Fingerprint,
  binary: Binary,
  hash: Hash,
  "letter-text": LetterText,
  "case-sensitive": CaseSensitive,
  calendar: Calendar,
  ruler: Ruler,
  lock: Lock,
  monitor: Monitor,
  layers: Layers,
  palette: Palette,
  search: Search,
  "file-text": FileText,
  "list-todo": ListTodo,
  sparkles: Sparkles,
  "toy-brick": Puzzle,
};

export function getIcon(name: string) {
  return iconMap[name] || HelpCircle;
}
